### ISSUE TITLE
1D simulation?

### ISSUE THREAD

**Issue by zhixwang** [kch3782/torcwa#5]
Hi, I wonder how shall the library be used for the 1D grating simulation properly & efficiently.

Thanks!

**Comment by kch3782** [comment]
Due to the high demand for 1D grating simulation, we have plans to update the 1D simulation classes and functions.

For now, 1D simulation can be performed by setting y-direction Fourier order to 0 (like order = [Fx, 0]) and the n_y value to 1, assuming that the structures are infinitely identical in the y-direction. The Ly value is irrelevant once the Fourier order is 0, but try to run the simulation with small Ly value as much as possible.

Thank you.

**Comment by zhixwang** [comment]
Thank you!
